Add PHP linting and compat actions
10up/wp-newrelic pull request #79
Opened 2024-11-01 11:13 UTC by jjgrainger

### Description of the Change
PR adds PHP linting and compat workflows.

Closes #78 

### How to test the Change

### Changelog Entry
> Developer - Add PHP linting and compat workflows

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [ ] All new and existing tests pass.

2024-11-08 15:00 UTC, faisal-alvi requested changes
@jjgrainger Thanks for the PR! I’ve added a couple of suggestions below. Additionally, it would be great to add a blank line at the end of each file for consistency.

2024-11-08 15:00 UTC, faisal-alvi commented on phpcs-compat.xml
> +	<arg name="extensions" value="php"/>
```suggestion
	<!-- Files to check -->
	<arg name="extensions" value="php"/>
```

2024-11-08 15:00 UTC, faisal-alvi commented on .github/workflows/php-compat.yml
> +      - "**.php"
Could you please add the PR branch `add/linting-php-compat-actions` to this list? This way, we can verify if the actions run and pass as expected.

2024-11-14 16:23 UTC, faisal-alvi requested changes
Seems like it did not trigger new checks on a PR, we’ll need to update the branches list under `pull_request` like this:

```
pull_request:
    branches:
      - develop
      - add/linting-php-compat-actions
```

2024-12-20 11:51 UTC, iamdharmesh commented
@faisal-alvi @jjgrainger The GitHub Actions workflow was not triggering because we have a PHP file paths filter in the workflow triggers, and there were no changes in any PHP files. I made a minor change in a PHP file to trigger the workflow, and it is working fine now. @faisal-alvi, could you please review this once again?

2024-12-23 18:36 UTC, faisal-alvi approved these changes

2024-12-23 19:49 UTC, merged